# Generated by Django 5.1.1 on 2024-09-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videoupload_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterModelTable(
            name='subtitle',
            table='video',
        ),
    ]
