# Generated by Django 5.1.1 on 2024-09-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videoupload_video_file_alter_subtitle_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subtitle',
            table='video_subtitles',
        ),
    ]
