# Generated by Django 5.1.1 on 2024-09-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_subtitle_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subtitle',
            table=None,
        ),
    ]
